version: "3"

services:
  db:
    image: mariadb:10.5
    container_name: novel-mysql-go
    volumes:
      - "/opt/Genshin-novel-reader-go-server/mysql-data:/var/lib/mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev
      - MYSQL_LOG_CONSOLE=true
      - lower_case_table_names=1

  redis:
    image: redis:5.0.7
    container_name: novel-redis-go
    ports:
      - 6379:6379
